### ISSUE TITLE
Comopuedo implementarlo??

### ISSUE THREAD

**Issue by henrypandales** [giansalex/sunat-sfs#1]
Atento saludo, quiero implementar este codigo en mi sistema de facturación
http://chamansos.com/ecyberx
Usuario: henry
Clave: henry

Por favor escribeme al whatsapp +57 314 775 4208
que estoy un poco perdido

**Comment by giansalex** [comment]
Hola, este repositorio incluía el codigo fuente de SUNAT SFS, pero si necesitas instalarlo, en [cpe.sunat](https://cpe.sunat.gob.pe/node/88#item-2) esta el manual .
